# .github/workflows/build-and-publish-images.yml
name: Build and push to DockerHub

on: workflow_dispatch

jobs:
  build_and_push_to_docker_hub:
    name: Push Docker images to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: {{cookiecutter.dockerhub_username}}
          {% raw %}password: ${{ secrets.DOCKERHUB_TOKEN }}{% endraw %}
      - name: Push to DockerHub
        run: |
          cp .env.example .env
          docker compose build
          docker compose push
